# Generated by Django 4.0.3 on 2022-03-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=50, unique=True, verbose_name='CPF')),
                ('data_admissao', models.DateField(verbose_name='Data Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data Demissão')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.departamento')),
            ],
        ),
    ]
