# Generated by Django 4.0.3 on 2022-03-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, verbose_name='Nome')),
                ('salario_base', models.FloatField(default=0, verbose_name='Salário Base')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=50, unique=True, verbose_name='CPF')),
                ('data_admissao', models.DateField(verbose_name='Data Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data Demissão')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('endereco_rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('endereco_numero', models.CharField(max_length=50, verbose_name='Numero')),
                ('endereco_bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('endereco_complemento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
                ('endereco_cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('endereco_cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('endereco_estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='GO', max_length=50, verbose_name='Estado')),
                ('salario', models.FloatField(default=0, verbose_name='Salário')),
                ('valor_diaria', models.FloatField(default=0, verbose_name='Diária')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.departamento')),
                ('funcao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.funcao')),
            ],
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(verbose_name='Entrada')),
                ('saida', models.DateTimeField(verbose_name='Saida')),
                ('tempo_total', models.IntegerField(default=0, verbose_name='Tempo Total')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(verbose_name='Mes')),
                ('fechada', models.BooleanField(default=False, verbose_name='Fechada')),
                ('salario_base', models.FloatField(default=0, verbose_name='Salário Base')),
                ('horas_extra', models.FloatField(default=0, verbose_name='Horas Extra')),
                ('faltas', models.FloatField(default=0, verbose_name='Faltas')),
                ('descontos', models.FloatField(default=0, verbose_name='Descontos')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificada', models.BooleanField(default=False, verbose_name='Justificada')),
                ('data', models.DateField(verbose_name='Data')),
                ('motivo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Motivo')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Dia')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
            ],
        ),
    ]
