# Generated by Django 4.0.3 on 2022-03-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, verbose_name='Nome')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='celular',
            field=models.CharField(default='', max_length=50, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco_bairro',
            field=models.CharField(default='', max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco_cep',
            field=models.CharField(default='', max_length=50, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco_complemento',
            field=models.CharField(max_length=50, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco_estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='GO', max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco_numero',
            field=models.CharField(default='', max_length=50, verbose_name='Numero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco_rua',
            field=models.CharField(default='', max_length=255, verbose_name='Rua'),
            preserve_default=False,
        ),
    ]
