# Generated by Django 4.0.3 on 2022-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_funcao_funcionario_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='endereco_cidade',
            field=models.CharField(default='Jatai', max_length=50, verbose_name='Cidade'),
            preserve_default=False,
        ),
    ]
