# Generated by Django 4.0.3 on 2022-03-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_funcionario_endereco_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.FloatField(default=0, verbose_name='Salário'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='valor_diaria',
            field=models.FloatField(default=0, verbose_name='Diária'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco_complemento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento'),
        ),
    ]
