# Generated by Django 4.0.3 on 2022-03-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_funcionario_salario_funcionario_valor_diaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(verbose_name='Entrada')),
                ('saida', models.DateTimeField(verbose_name='Saida')),
                ('tempo_total', models.IntegerField(default=0, verbose_name='Tempo Total')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificada', models.BooleanField(default=False, verbose_name='Justificada')),
                ('data', models.DateField(verbose_name='Data')),
                ('motivo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Motivo')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
            ],
        ),
    ]
