# Generated by Django 4.0.3 on 2022-03-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_horaextra_falta'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='valor',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
    ]
