# Generated by Django 4.0.3 on 2022-03-11 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_horaextra_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcao',
            name='salario_base',
            field=models.FloatField(default=0, verbose_name='Salário Base'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rh.funcao'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Dia')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
            ],
        ),
    ]
