# Generated by Django 4.0.3 on 2022-03-11 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_remove_funcionario_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.funcao'),
        ),
    ]
