# Generated by Django 4.0.3 on 2022-03-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_funcionario_funcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(verbose_name='Mes')),
                ('fechada', models.BooleanField(default=False, verbose_name='Fechada')),
                ('salario_base', models.FloatField(verbose_name='Salário Base')),
                ('horas_extra', models.FloatField(verbose_name='Horas Extra')),
                ('descontos', models.FloatField(verbose_name='Descontos')),
                ('total', models.FloatField(verbose_name='Total')),
                ('faltas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.falta')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
            ],
        ),
    ]
