# Generated by Django 4.0.3 on 2022-03-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_folhapagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhapagamento',
            name='faltas',
            field=models.FloatField(verbose_name='Faltas'),
        ),
    ]
