# Generated by Django 4.0.3 on 2022-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0011_alter_folhapagamento_faltas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhapagamento',
            name='descontos',
            field=models.FloatField(default=0, verbose_name='Descontos'),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='faltas',
            field=models.FloatField(default=0, verbose_name='Faltas'),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='horas_extra',
            field=models.FloatField(default=0, verbose_name='Horas Extra'),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='salario_base',
            field=models.FloatField(default=0, verbose_name='Salário Base'),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
    ]
