# Generated by Django 4.0.3 on 2022-03-14 20:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0012_alter_folhapagamento_descontos_and_more'),
        ('servico', '0004_alter_servico_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor_total', models.FloatField(verbose_name='Valor Total')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('quantidade', models.IntegerField(default=0, verbose_name='QTD')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor_total', models.FloatField(verbose_name='Valor Total')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.servico')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=1, verbose_name='Quantidade')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.item')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.saida')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=1, verbose_name='Quantidade')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.entrada')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.item')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('data_emprestimo', models.DateField(default=datetime.datetime(2022, 3, 14, 17, 14, 59, 33951), verbose_name='Data Empréstimo')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Devolução')),
                ('devolvido', models.BooleanField(default=False, verbose_name='Foi Devolvido')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.item')),
            ],
        ),
    ]
