# Generated by Django 4.0.3 on 2022-03-30 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('data_emprestimo', models.DateField(default=datetime.datetime(2022, 3, 30, 17, 8, 8, 307742), verbose_name='Data Empréstimo')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Devolução')),
                ('devolvido', models.BooleanField(default=False, verbose_name='Foi Devolvido')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor_total', models.FloatField(verbose_name='Valor Total')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=1, verbose_name='Quantidade')),
                ('valor', models.FloatField(verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('quantidade', models.IntegerField(default=0, verbose_name='QTD')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor_total', models.FloatField(verbose_name='Valor Total')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=1, verbose_name='Quantidade')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.item')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.saida')),
            ],
        ),
    ]
