# Generated by Django 4.0.3 on 2022-03-17 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2022, 3, 17, 15, 18, 57, 933717), verbose_name='Data Empréstimo'),
        ),
    ]
