# Generated by Django 4.0.3 on 2022-03-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0001_initial'),
        ('rh', '0001_initial'),
        ('almox', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaitem',
            name='compra_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.compraitem'),
        ),
        migrations.AddField(
            model_name='entradaitem',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.entrada'),
        ),
        migrations.AddField(
            model_name='entradaitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.item'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.compra'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.ordemservico'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.item'),
        ),
    ]
