# Generated by Django 4.0.3 on 2022-03-30 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almox', '0004_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2022, 3, 30, 17, 9, 28, 208936), verbose_name='Data Empréstimo'),
        ),
    ]
