# Generated by Django 4.0.3 on 2022-03-18 20:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_compraitem_valor_total'),
        ('almox', '0006_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.compra'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2022, 3, 18, 17, 21, 20, 282041), verbose_name='Data Empréstimo'),
        ),
    ]
