# Generated by Django 4.0.3 on 2022-03-18 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_compraitem_valor_total'),
        ('almox', '0007_entrada_compra_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaitem',
            name='compra_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.compraitem'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2022, 3, 18, 17, 22, 17, 553935), verbose_name='Data Empréstimo'),
        ),
    ]
