# Generated by Django 4.0.3 on 2022-03-22 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almox', '0010_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 17, 3, 17, 838073), verbose_name='Data Empréstimo'),
        ),
    ]
