# Generated by Django 4.0.3 on 2022-03-24 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almox', '0011_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 16, 25, 28, 282164), verbose_name='Data Empréstimo'),
        ),
    ]
