# Generated by Django 4.0.3 on 2022-03-29 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almox', '0015_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2022, 3, 29, 15, 46, 33, 408369), verbose_name='Data Empréstimo'),
        ),
    ]
