# Generated by Django 4.0.3 on 2022-03-29 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0008_alter_ordemservico_conclusao'),
        ('almox', '0016_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='servico',
        ),
        migrations.AddField(
            model_name='entrada',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.ordemservico'),
        ),
        migrations.AddField(
            model_name='saida',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.ordemservico'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2022, 3, 29, 16, 14, 8, 763577), verbose_name='Data Empréstimo'),
        ),
    ]
