# Generated by Django 4.0.3 on 2022-03-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=1024, verbose_name='Tipo')),
                ('cpf', models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='CNPJ')),
            ],
        ),
    ]
