# Generated by Django 4.0.3 on 2022-03-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_alter_cliente_cnpj_alter_cliente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, verbose_name='Nome')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data')),
                ('data_conclusao', models.DateField(verbose_name='Data Conclusão')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
