# Generated by Django 4.0.3 on 2022-03-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('conclusao', models.DateField(blank=True, null=True, verbose_name='Conclusão')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1024, verbose_name='Descrição')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='ServicosOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=1, verbose_name='Quantidade')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.ordemservico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.servico')),
            ],
        ),
    ]
