# Generated by Django 4.0.3 on 2022-03-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, verbose_name='Nome')),
                ('valor', models.FloatField(verbose_name='Valor')),
            ],
        ),
    ]
