# Generated by Django 4.0.3 on 2022-03-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_tiposervico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='nome',
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.CharField(default='', max_length=1024, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='servico.tiposervico'),
            preserve_default=False,
        ),
    ]
