# Generated by Django 4.0.3 on 2022-03-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_remove_servico_nome_servico_descricao_servico_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
    ]
