# Generated by Django 4.0.3 on 2022-03-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_alter_servico_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='concluido',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='data',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='TipoServico',
        ),
    ]
