# Generated by Django 4.0.3 on 2022-03-29 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_cnpj_alter_cliente_cpf'),
        ('servico', '0005_remove_servico_cliente_remove_servico_concluido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('conslusao', models.DateField(verbose_name='Conclusão')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ServicosOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=1, verbose_name='Quantidade')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.ordemservico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.servico')),
            ],
        ),
    ]
