# Generated by Django 4.0.3 on 2022-03-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0006_ordemservico_servicosos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='conslusao',
            new_name='conclusao',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='descricao',
            field=models.CharField(default='', max_length=255, verbose_name='Descricao'),
            preserve_default=False,
        ),
    ]
