# Generated by Django 4.0.3 on 2022-03-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0007_rename_conslusao_ordemservico_conclusao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Conclusão'),
        ),
    ]
