# Generated by Django 4.0.3 on 2022-03-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0012_alter_folhapagamento_descontos_and_more'),
        ('almox', '0002_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('forma_pagamento', models.CharField(choices=[('avista', 'À Vista'), ('1x', 'Parcelado em 1x'), ('2x', 'Parcelado em 2x'), ('3x', 'Parcelado em 3x'), ('4x', 'Parcelado em 4x'), ('5x', 'Parcelado em 5x'), ('6x', 'Parcelado em 6x'), ('7x', 'Parcelado em 7x'), ('8x', 'Parcelado em 8x'), ('9x', 'Parcelado em 9x'), ('10x', 'Parcelado em 10x'), ('11x', 'Parcelado em 11x'), ('12x', 'Parcelado em 12x')], default='avista', max_length=50, verbose_name='Forma de Pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=50, unique=True, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('quantidade', models.FloatField(verbose_name='Quantidade')),
                ('estoque', models.BooleanField(default=True, verbose_name='Estoque')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.compra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.item')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.fornecedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.funcionario'),
        ),
    ]
