# Generated by Django 4.0.3 on 2022-03-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='descricao',
            field=models.CharField(default='', max_length=1024, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='entregue',
            field=models.BooleanField(default=False, verbose_name='Entregue'),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_total',
            field=models.FloatField(default=0, verbose_name='Valor Total'),
            preserve_default=False,
        ),
    ]
