# Generated by Django 4.0.3 on 2022-03-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_descricao_compra_entregue_compra_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='valor_total',
            field=models.FloatField(default=0, verbose_name='Valor Total'),
        ),
    ]
