# Generated by Django 4.0.3 on 2022-03-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_alter_compra_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraitem',
            name='valor_total',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
    ]
