# Generated by Django 4.0.3 on 2022-03-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_compraitem_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraitem',
            name='recebido',
            field=models.BooleanField(default=False, verbose_name='Recebido'),
        ),
    ]
