# Generated by Django 4.0.3 on 2022-03-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_compraitem_recebido'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='concluida',
            field=models.BooleanField(default=False, verbose_name='Concluida'),
        ),
    ]
