# Generated by Django 4.0.3 on 2022-03-29 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_contasreceber_alter_contaspagar_data_recebimentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaspagar',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 15, 26, 14, 302923), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 15, 26, 14, 304279), verbose_name='Data'),
        ),
    ]
