# Generated by Django 4.0.3 on 2022-03-29 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_alter_contaspagar_data_alter_contasreceber_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaspagar',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 16, 14, 8, 752636), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 16, 14, 8, 753862), verbose_name='Data'),
        ),
    ]
